# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
      user_db:
        entity: { class: AppBundle\Entity\User }

    encoders:
      AppBundle\Entity\User: bcrypt

    role_hierarchy:
      ROLE_ADMIN: ROLE_USER

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html

            form_login:
              login_path: login
              check_path: login
              csrf_token_generator: security.csrf.token_manager
            logout:
              path: /logout
              target: /

            remember_me:
              secret: '%secret%'

    access_control:
      - { path: ^/admin, roles: ROLE_ADMIN }
      - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }